version: 0.2

phases:
  install:
    commands:
      - npm install
  build:
    commands:
      - aws cloudformation package
          --template-file samTemplate.yaml
          --s3-bucket $S3_BUCKET
          --s3-prefix $S3_PREFIX
          --output-template-file NewSamTemplate.yaml
artifacts:
  files:
    - NewSamTemplate.yaml
